name: Haskell CI

on: 
  pull_request:
  push:

jobs:
  vm-job:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
        - 6379/tcp
        options: --entrypoint redis-server

    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v6
    - uses: cachix/cachix-action@v2
      with:
        name: 573-ci
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
# https://github.com/actions/example-services/blob/master/.github/workflows/redis-service.yml uses - run: ... with a working-directory: ./redis here which is not allowed for cachix-action, would need to have an extra run: step as with cachix/install-nix-action@v6
      env:
        REDIS_HOST: localhost
        REDIS_PORT: ${{ job.services.redis.ports[6379] }}
