name: Haskell CI

on: 
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v6
    - run: |
        nix-env -f https://github.com/NixOS/nixpkgs-channels/archive/nixos-17.09.tar.gz -iA redis
        redis-server &
    - run: redis-cli ping
    - uses: cachix/cachix-action@v2
      with:
        name: 573-ci
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: redis-cli ping
    - run: redis-cli shutdown
     
#  build:

#    runs-on: ubuntu-latest

#    steps:
#    - uses: actions/checkout@v1
#    - uses: actions/setup-haskell@v1
#      with:
#        ghc-version: '8.6.5'
#        cabal-version: '3.0'
#    - name: Install dependencies
#      run: |
#        cabal update
#        cabal install --only-dependencies --enable-tests
#    - name: Build
#      run: |
#        cabal configure --enable-tests
#        cabal build
#    - name: Run tests
#      run: cabal test
